### ISSUE TITLE
Mekanism Metals TODO

### ISSUE THREAD

**Issue by justinrusso** [Darkosto/SevTech-Ages#431]
- [ ] Add osmium to globals
- [ ] Add stage for osmium in `metals.zs`
- [ ] Oredict all metal stuff, since oredict is done late in mekanism. (or report it and maybe get it fixed)
- [ ] Figure out what metals to add mekanism's parts to (crystal, shard, dirty dust, clump) and add them
