### ISSUE TITLE
TODO recipes

### ISSUE THREAD

**Issue by justinrusso** [Darkosto/SevTech-Ages#455]
Cleaning these out of the code or theyll never be noticed:

### Three:
- [ ] `<minecraft:cauldron>`
- [ ] `<minecraft:milk_bucket>`
- [ ] `<minecraft:lava_bucket>`
- [ ] `<minecraft:water_bucket>`
- [ ] `<minecraft:name_tag>`
- [ ] `<minecraft:tripwire_hook>`
- [ ] `<minecraft:lapis_block>`
- [ ] `<minecraft:dye:4>`
- [ ] `<cyclicmagic:tool_auto_torch>`
- [ ] `<cyclicmagic:wand_missile>`
- [ ] `<cyclicmagic:fire_killer>`
- [ ] `<cyclicmagic:purple_boots>`
- [ ] `<cyclicmagic:charm_wing>`
- [ ] `<cyclicmagic:gold_furnace_minecart>`
- [ ] `<cyclicmagic:turret_minecart>`
- [ ] `<cyclicmagic:password_block>`
- [ ] `<cyclicmagic:plate_push_fast>`
- [ ] `<cyclicmagic:ender_blaze>`
- [ ] `<cyclicmagic:chest_sack_empty>`
- [ ] `<cyclicmagic:entity_detector>`
- [ ] `<cyclicmagic:tool_swap>`
- [ ] `<cyclicmagic:charm_fire>`
- [ ] `<cyclicmagic:gold_minecart>`
- [ ] `<cyclicmagic:stone_minecart>`
- [ ] `<cyclicmagic:plate_push>`
- [ ] `<cyclicmagic:magnet_anti_block>`
- [ ] `<cyclicmagic:ender_water>`
- [ ] `<cyclicmagic:chest_sack>`
- [ ] `<cyclicmagic:carbon_paper>`
- [ ] `<cyclicmagic:purple_chestplate>`
- [ ] `<cyclicmagic:purple_helmet>`
- [ ] `<cyclicmagic:sprinkler>`
- [ ] `<cyclicmagic:block_hydrator>`
- [ ] `<cyclicmagic:dropper_minecart>`
- [ ] `<cyclicmagic:horse_upgrade_speed>`
- [ ] `<cyclicmagic:plate_push_slowest>`
- [ ] `<cyclicmagic:ender_snow>`
- [ ] `<cyclicmagic:evoker_fang>`
- [ ] `<cyclicmagic:tool_push>`
- [ ] `<cyclicmagic:fire_dark>`
- [ ] `<cyclicmagic:horse_upgrade_jump>`
- [ ] `<abyssalcraft:crystal:*>`
- [ ] `<abyssalcraft:crystalshard:*>`
- [ ] `<abyssalcraft:crystalcluster:*>`
- [ ] `<abyssalcraft:crystalcluster2:*>`
- [ ] `<abyssalcraft:crystalfragment:*>`
- [ ] `<abyssalcraft:transmutator>`
- [ ] `<abyssalcraft:transmutationgem>`

### Two:
- [ ] `<cyclicmagic:block_fragile_weak>`
- [ ] `<cyclicmagic:ender_lightning>`
- [ ] `<cyclicmagic:water_freezer>`
- [ ] `<cyclicmagic:apple_lapis>`
- [ ] `<cyclicmagic:spikes_iron>`
- [ ] `<cyclicmagic:horse_upgrade_variant>`
- [ ] `<cyclicmagic:tool_spawn_inspect>`
- [ ] `<cyclicmagic:block_fragile>`
- [ ] `<cyclicmagic:tool_torch_launcher>`
- [ ] `<cyclicmagic:mattock>`
- [ ] `<cyclicmagic:tool_rotate>`
- [ ] `<cyclicmagic:tool_trade>`
- [ ] `<cyclicmagic:block_soundproofing>`
- [ ] `<cyclicmagic:block_fragile_auto>`
- [ ] `<cyclicmagic:food_step>`
- [ ] `<cyclicmagic:tool_spelunker>`
- [ ] `<cyclicmagic:charm_water>`
- [ ] `<cyclicmagic:charm_speed>`
- [ ] `<cyclicmagic:charm_antidote>`
- [ ] `<cyclicmagic:block_fishing>`
- [ ] `<cyclicmagic:tool_harvest_crops>`
- [ ] `<cyclicmagic:ender_dungeon>`

### Two:
*Noted in file: Recipes needed for this stage - create later*
- [ ] `<minecraft:spectral_arrow>`
- [ ] `<minecraft:tipped_arrow:*>`
- [ ] `<betterwithmods:broadhead_arrow>`
- [ ] `<betterwithaddons:material>`
- [ ] `<betterwithaddons:greatarrow>`
- [ ] `<betterwithaddons:bundle:*>`
- [ ] `<enderutilities:enderarrow>`
- [ ] `<primal:arrow_torch_nether>`
- [ ] `<primal:arrow_torch_redstone>`
- [ ] `<quark:arrow_ender>`
- [ ] `<quark:arrow_explosive>`
- [ ] `<betterwithmods:material:43>`
- [ ] `<primal:ironwood_bow>`
- [ ] `<primal:corypha_bow>`
- [ ] `<abyssalcraft:corbow>`
- [ ] `<betterwithmods:composite_bow>`
- [ ] `<betterwithaddons:greatbow>`
- [ ] `<enderutilities:enderbow>`
- [ ] `<totemic:baykok_bow>`
- [ ] `<natura:materials:5>`

### Recipes Needed:

- [ ] `<minecraft:jukebox>`
- [ ] `<animalium:dog_boots>`

- [ ] `<betterbuilderswands:wandunbreakable>`

- [ ] `<rangedpumps:pump>`
- [ ] `<primal:fish_trap>`
- [ ] `<primal:fish_trap:1>`
- [ ] `<primal:fish_trap:2>`
- [ ] `<primal:fish_trap:3>`
- [ ] `<primal:fish_trap:4>`
- [ ] `<primal:fish_trap:5>`
- [ ] `<primal:fish_trap:6>`
- [ ] `<primal:fish_trap:7>`
- [ ] `<primal:fish_trap:8>`
- [ ] `<primal:fish_trap:9>`

- [ ] `<pickletweaks:reinforced_mesh>`
- [ ] `<pickletweaks:repair_kit>`

- [ ] `<betterwithmods:anchor>`
- [ ] `<betterwithmods:single_machine:1>`

- [ ] `<betterwithmods:manual>`

- [ ] `<geolosys:field_manual>`

- [ ] `<betterwithmods:raw_scrambled_egg>`

- [ ] `<natura:colored_grass_slab:2>`
- [ ] `<natura:colored_grass_slab:1>`
- [ ] `<natura:colored_grass_slab>`
- [ ] `<natura:colored_grass:2>`
- [ ] `<natura:colored_grass:1>`
- [ ] `<natura:colored_grass>`

- [ ] Orion Drive

- [ ] `<galacticraftcore:glowstone_torch>`
- [ ] `<galacticraftcore:basic_block_core:4>`
- [ ] `<galacticraftcore:space_glass_clear>`
- [ ] `<galacticraftcore:air_lock_frame>`
- [ ] `<galacticraftcore:space_glass_clear:1>`

- [ ] Weighted Pressure Plate

- [ ] `<natura:overworld_doors>`

**Comment by JackRuby1** [comment]
@justinrusso - that cyclic mattock still isn't staged, and I'm not making another issue if it's already in one...like here :P
